import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Upperheader from "./components/Upperheader";
import Middleheader from "./components/Middleheader";
import Lastheader from "./components/Lastheader";
import { Footer } from "./components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body > 
        <Upperheader/>
        <Middleheader/>
      <Lastheader/>
        {children}
        <Footer/></body>
    </html>
  )
}
